name: spectrum_support
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_pagewise: ^2.0.4
  path_provider: ^2.1.4
  flutter_pdfview: ^1.3.3
  shared_preferences: ^2.3.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  firebase_messaging: ^15.1.3
  provider: ^6.1.2
  flutter_form_builder: ^9.4.1
  http: ^1.2.2
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  flutter_local_notifications: ^17.2.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
  sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/videos/
